# encoding: utf-8

site :opscode

cookbook 'apt'
cookbook 'git'

# docker!
cookbook "docker", github: "bflad/chef-docker"
# See: https://github.com/NOX73/chef-golang/pull/4
# cookbook "golang", github: "NOX73/chef-golang"
cookbook "golang", github: "buth/chef-golang", ref: "lwrps"
cookbook "lxc", github: "hw-cookbooks/lxc"
cookbook "modules", github: "Youscribe/modules-cookbook"

