# encoding: utf-8

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true

  config.vm.box = "opscode_ubuntu-13.04_provisionerless"
  config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box"

  config.vm.network :private_network, ip: "10.255.255.11"
  config.vm.synced_folder "~/code", "/code"

  config.vm.provision :chef_solo do |chef|

    chef.json = {
    }

    chef.run_list = [
      "recipe[apt]",
      "recipe[git]",
      "recipe[docker]"
    ]

  end
end
